### ISSUE TITLE
Keeping Header unencrypted for blind seeding?

### ISSUE THREAD

**Issue by Nazeh** [hypercore-protocol/hyperdrive-next#3]
I wonder if there are any privacy problems in leaving the header of `drive.core` in plain text, to help services like [simple-seeder](https://github.com/mafintosh/simple-seeder) blind seed an otherwise encrypted drive using one key.

Basically using a `core.session()` to add encryption _after_ the header is already written.

**Comment by mafintosh** [comment]
I think that’s fine, but tonight I’m pushing out an update to sodium-native that allows tweaking apis, so we don’t need the header at all

**Comment by Nazeh** [comment]
Sounds like magic! watching that.
